name: Project Checks

on:
  push:
    branches:
      - main
      - "release/**"
      - "test/**"
  pull_request:
    branches:
      - main
      - "release/**"

env:
  GO_VERSION: "1.19.5"

jobs:
  checkout:
    name: checkout
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      - name: checkout code
        uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/nri-plugin-collection
          fetch-depth: 25

  verify: 
    name: verify
    uses: src/github.com/containerd/nri-plugin-collection
    needs: checkout
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make verify
        run: |
          make verify
        working-directory: src/github.com/containerd/nri-plugin-collection
        